version: '3'

services:
  mongo:
    image: mongo:4.0.5-xenial
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - 'mongo_volume:/data/db'
    ports:
      - '27017:27017'
    command: mongod --smallfiles

  mongo-express:
    image: mongo-express:0.49.0
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - '8081:8081'
    depends_on:
      - mongo

  strapi:
    image: strapi/strapi:v3.0.0-alpha.14.5
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_NAME: strapi
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
    ports:
      - '1337:1337'
    depends_on:
      - mongo

volumes:
  mongo_volume:
    driver: local
